app = "deathspace-coruja"
primary_region = "gru"

[build]
  builder = "heroku/builder:24"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/dist"
  url_prefix = "/"